project_name: github-cli

before:
  hooks:
  - go mod download

builds:
- id: github-cli
  binary: github-cli
  ldflags: "-s -w -X github.com/twpayne/github-cli/cmd.Version={{ .Version }} -X github.com/twpayne/github-cli/cmd.Commit={{ .Commit }} -X github.com/twpayne/github-cli/cmd.Date={{ .Date }}"
  goos:
  - linux
  - darwin
  goarch:
  - amd64

archives:
- builds:
  - github-cli
  files:
  - LICENSE
  - README.md
  replacements:
    386: i386
  format_overrides:
  - goos: windows
    format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - "Merge pull request"
    - "Merge branch"
