on:
  push:
jobs:
  ubuntu-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Build
      run: go build ./...
    - name: Run
      run: go run . --version
    - name: Test
      run: go test -race ./...
    - name: Lint
      run: |
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- v1.21.0
        ./bin/golangci-lint run
    - name: Check formatting
      run: |
        GO111MODULE=off go get -u mvdan.cc/gofumpt/gofumports
        find . -name '*.go' | xargs $(go env GOPATH)/bin/gofumports -w
        git diff --exit-code
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs:
    - ubuntu-ci
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Go modules
      run: go mod download
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo chown root:root /
        sudo snap install goreleaser --classic
        goreleaser release